#!/usr/bin/env node
'use strict';

/**
 * generate-page.js
 * -----------------
 * Standalone tool (Node 18+) so you can fill in the real puzzles/answers
 * yourself without having to write any crypto code. This script is NOT part
 * of the live site -- run it locally and paste the output into the relevant
 * HTML page.
 *
 * Usage (see README.md for the full walkthrough + examples):
 *
 *   node generate-page.js --password "secret" --text "literal text"
 *   node generate-page.js --password "secret" --file page2-payload.json
 *   node generate-page.js --image path/to/photo.jpg
 *   node generate-page.js --caesar --shift 7 --text "message"
 *   node generate-page.js --encode-stack --text "message"
 *   node generate-page.js --sha256 --text "candidate answer"
 *
 * The main mode (--password + --text/--file) hashes the password (SHA-256)
 * and encrypts the given text with AES-GCM, deriving the key via PBKDF2
 * (100,000 iterations by default, fixed salt) from the password. The output
 * contains ready-to-paste JS constants for the `// FILL IN ... HERE` spot in
 * the relevant page.
 */

const fs = require('node:fs');
const path = require('node:path');
const { webcrypto } = require('node:crypto');
const subtle = webcrypto.subtle;

const DEFAULT_SALT = 'heimdal-arg-fixed-salt-value-2025';
const DEFAULT_ITERATIONS = 100000;

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const tok = argv[i];
    if (tok.startsWith('--')) {
      const key = tok.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith('--')) {
        args[key] = true;
      } else {
        args[key] = next;
        i++;
      }
    } else {
      args._.push(tok);
    }
  }
  return args;
}

function bytesToBase64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

async function sha256Hex(text) {
  const digest = await subtle.digest('SHA-256', new TextEncoder().encode(text));
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function deriveAesKey(password, saltStr, iterations) {
  const keyMaterial = await subtle.importKey(
    'raw',
    new TextEncoder().encode(password),
    { name: 'PBKDF2' },
    false,
    ['deriveKey']
  );
  return subtle.deriveKey(
    { name: 'PBKDF2', salt: new TextEncoder().encode(saltStr), iterations, hash: 'SHA-256' },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt']
  );
}

async function encryptText(plaintext, password, saltStr, iterations) {
  const key = await deriveAesKey(password, saltStr, iterations);
  const iv = webcrypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    new TextEncoder().encode(plaintext)
  );
  return {
    ciphertextB64: bytesToBase64(new Uint8Array(ciphertext)),
    ivB64: bytesToBase64(iv),
  };
}

// ---- Caesar cipher utility (the shift key stays local only, never in the site) ----
function caesarShift(text, shift) {
  const n = ((shift % 26) + 26) % 26;
  return text.replace(/[a-zA-Z]/g, (ch) => {
    const base = ch <= 'Z' ? 65 : 97;
    return String.fromCharCode(((ch.charCodeAt(0) - base + n) % 26) + base);
  });
}

// ---- Encoding-stack utility: plaintext -> hex -> rot13 -> base64 ----
function rot13(text) {
  return text.replace(/[a-zA-Z]/g, (ch) => {
    const base = ch <= 'Z' ? 65 : 97;
    return String.fromCharCode(((ch.charCodeAt(0) - base + 13) % 26) + base);
  });
}

function toHex(text) {
  return Buffer.from(text, 'utf8').toString('hex');
}

function encodeStack(text) {
  const hexStep = toHex(text);
  const rotStep = rot13(hexStep);
  const b64Step = Buffer.from(rotStep, 'utf8').toString('base64');
  return b64Step;
}

function printBlock(lines) {
  console.log('\n// ---- Generated by generate-page.js (' + new Date().toISOString() + ') ----');
  for (const line of lines) console.log(line);
  console.log('// -----------------------------------------------------------------\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help || args.h) {
    console.log(fs.readFileSync(__filename, 'utf8').split('\n').slice(1, 30).join('\n'));
    return;
  }

  // --- Utility: image -> data URL (no crypto, just to paste into a JSON payload) ---
  if (args.image) {
    const filePath = path.resolve(String(args.image));
    const data = fs.readFileSync(filePath);
    const ext = path.extname(filePath).slice(1).toLowerCase();
    const mimeMap = { jpg: 'jpeg', svg: 'svg+xml' };
    const mime = mimeMap[ext] || ext || 'png';
    const dataUrl = `data:image/${mime};base64,${data.toString('base64')}`;
    printBlock([`Data URL for ${filePath}:`, dataUrl]);
    return;
  }

  // --- Utility: Caesar cipher (set the shift locally, NEVER paste it into the site) ---
  if (args.caesar) {
    if (!args.text || !args.shift) {
      console.error('Usage: node generate-page.js --caesar --shift <number> --text "<message>"');
      process.exit(1);
    }
    const shifted = caesarShift(String(args.text), parseInt(args.shift, 10));
    printBlock([
      `Caesar shift: ${args.shift} (do NOT put this value on the site, only in the club song)`,
      `Ciphertext to show on the page:`,
      shifted,
    ]);
    return;
  }

  // --- Utility: encoding-stack (hex -> rot13 -> base64) ---
  if (args['encode-stack']) {
    if (!args.text) {
      console.error('Usage: node generate-page.js --encode-stack --text "<message>"');
      process.exit(1);
    }
    const encoded = encodeStack(String(args.text));
    printBlock([
      'Encoding-stack result (player must peel back: base64 -> rot13 -> hex):',
      encoded,
    ]);
    return;
  }

  // --- Utility: sha256 of a candidate answer (for the hash-crack page) ---
  if (args.sha256) {
    if (!args.text) {
      console.error('Usage: node generate-page.js --sha256 --text "<answer>"');
      process.exit(1);
    }
    const hash = await sha256Hex(String(args.text));
    printBlock(['SHA-256 hash to use as the target on the hash-crack page:', hash]);
    return;
  }

  // --- Main mode: password hash + AES-GCM encrypted payload ---
  if (!args.password) {
    console.error(
      'Usage:\n' +
        '  node generate-page.js --password "secret" --text "literal text"\n' +
        '  node generate-page.js --password "secret" --file payload.json\n' +
        '  node generate-page.js --image path/to/photo.jpg\n' +
        '  node generate-page.js --caesar --shift 7 --text "message"\n' +
        '  node generate-page.js --encode-stack --text "message"\n' +
        '  node generate-page.js --sha256 --text "candidate answer"'
    );
    process.exit(1);
  }

  if (!args.text && !args.file) {
    console.error('Provide --text "..." or --file <path> with the content to encrypt.');
    process.exit(1);
  }

  const password = String(args.password);
  const plaintext = args.file
    ? fs.readFileSync(path.resolve(String(args.file)), 'utf8')
    : String(args.text);
  const salt = args.salt ? String(args.salt) : DEFAULT_SALT;
  const iterations = args.iterations ? parseInt(args.iterations, 10) : DEFAULT_ITERATIONS;

  const passwordHash = await sha256Hex(password);
  const { ciphertextB64, ivB64 } = await encryptText(plaintext, password, salt, iterations);

  printBlock([
    `const PASSWORD_HASH = "${passwordHash}";`,
    `const PBKDF2_SALT = "${salt}";`,
    `const PBKDF2_ITERATIONS = ${iterations};`,
    `const CIPHERTEXT = "${ciphertextB64}";`,
    `const IV = "${ivB64}";`,
  ]);
  console.log(
    'Paste these 5 lines into the page at the `// FILL IN ... HERE` spot.\n' +
      'Note: if you generate for the SAME page more than once (e.g. text + a separate payload\n' +
      'file), reuse the same password + the same --salt each time so PASSWORD_HASH and\n' +
      'PBKDF2_SALT stay identical everywhere -- only CIPHERTEXT and IV are unique per run.'
  );
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
